CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'alyazici'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'alyazici'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'test';
